version: '3.8'

services:
  image_previewer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    volumes:
      - ./configs:/app/configs  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/test_images:/usr/share/nginx/html/test_images
    depends_on:
      - image_previewer

