name: CI

on:
  push:
    branches:
      - main  # Запускать при пуше в главную ветку (или укажите ваши нужные ветки)
  pull_request:
    branches:
      - main  # Запускать при Pull Request в главную ветку

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'  # Указываем версию Go

      - name: Install golangci-lint
        run: |
          sudo curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest

      - name: Run golangci-lint
        run: golangci-lint run --config=.golangci.yml  # Укажите путь к вашему конфигу

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'  # Указываем версию Go

      - name: Run unit tests
        run: go test -race -count=100 ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'  # Указываем версию Go

      - name: Build binary
        run: |
          mkdir -p ./bin
          go build -o ./bin/image_previewer ./cmd/image_previewer  
